version: "3.7"

services:
    app:
        build:
          context: ./
          dockerfile: Dockerfile
        image: sunspottours
        container_name: sunspottours-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            -   ./:/var/www
        depends_on:
            - redis
        networks:
            -   sunspottours

    nginx:
        image: nginx:1.17.10-alpine
        container_name: sunspottours-nginx
        restart: unless-stopped
        ports:
            -   "80:80"
        volumes:
            -   ./:/var/www
            -   ./.docker/nginx:/etc/nginx/conf.d
        networks:
            -   sunspottours

    redis:
        image: redis:latest
        container_name: sunspottours_redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            - sunspottours

networks:
    sunspottours:
        driver: bridge
